const $=id=>document.getElementById(id);
let current=null;
const iso=d=>d.toISOString().slice(0,10);
function localISO(d=new Date()){let x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function records(){return JSON.parse(localStorage.getItem('rpgaRecords')||'[]')}
function putRecords(r){localStorage.setItem('rpgaRecords',JSON.stringify(r))}
function key(date,lesson){return date+'-L'+lesson}
function pct(rec){let vals=Object.values(rec.checks||{});return vals.length?Math.round(vals.filter(Boolean).length/vals.length*100):0}
function showTab(id){['home','workout','target','history','report'].forEach(x=>$(x).classList.toggle('hidden',x!==id));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('on'));let n=$('n-'+id);if(n)n.classList.add('on');if(id==='home')renderHome();if(id==='target')renderTarget();if(id==='history')renderHistory();if(id==='report')renderReport();scrollTo(0,0)}
function startWorkout(){let date=$('workDate').value,lesson=$('lesson').value;let old=records().find(r=>r.key===key(date,lesson));current=old||{key:key(date,lesson),date,lesson,checks:{},saved:false,workoutType:'Independent',startTime:'',totalMinutes:'',coachNotes:'',selfNotes:'',elapsedSeconds:0,timerRunning:false,timerStartedAt:null};renderWorkout();showTab('workout')}
function addExercise(parent,name,reps,url,id){let row=document.createElement('div');row.className='ex';row.innerHTML=`<input type="checkbox" ${current.checks[id]?'checked':''}><div><div class="name">${name}</div><div class="reps">${reps}</div></div>${url?`<a class="video" target="_blank" href="${url}">â¶ Video</a>`:''}`;let cb=row.querySelector('input');cb.onchange=()=>{current.checks[id]=cb.checked;autosave()};parent.appendChild(row)}
function renderWorkout(){let body=$('workoutBody');body.innerHTML='';$('workoutTitle').innerHTML=`<div class="card pad"><div class="date">${new Date(current.date+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</div><h2>Lesson ${current.lesson}</h2></div>`;let c=document.createElement('div');c.className='card';c.innerHTML='<div class="sectionTitle">Warm-Up</div>';WARM.forEach((e,i)=>addExercise(c,e[0],e[1],'','warm-'+i));body.appendChild(c);LESSONS[current.lesson].forEach((s,si)=>{let c=document.createElement('div');c.className='card';c.innerHTML=`<div class="sectionTitle">${s[0]}</div>`;for(let round=1;round<=s[1];round++){let h=document.createElement('div');h.className='round';h.textContent=`Round ${round} of ${s[1]}`;c.appendChild(h);s[2].forEach((e,ei)=>addExercise(c,e[0],e[1],e[2],`${si}-${round}-${ei}`))}body.appendChild(c)});let rc=document.createElement('div');rc.className='card';rc.innerHTML='<div class="sectionTitle">Recovery</div>';RECOVERY.forEach((e,i)=>addExercise(rc,e[0],e[1],'','recovery-'+i));body.appendChild(rc);
setTimeout(()=>{let wt=current.workoutType||'Independent';document.querySelectorAll('input[name="workoutType"]').forEach(x=>x.checked=x.value===wt);$('startTime').value=current.startTime||'';$('totalMinutes').value=current.totalMinutes||'';$('coachNotes').value=current.coachNotes||'';$('selfNotes').value=current.selfNotes||'';renderTimer()},0)}
function autosave(){let rs=records(),i=rs.findIndex(r=>r.key===current.key);if(i>=0)rs[i]=current;else rs.push(current);putRecords(rs)}
function saveWorkout(){setMeta();if(!current.workoutType)current.workoutType='Independent';if(current.timerRunning){stopTimer()}if(!current.totalMinutes && (current.elapsedSeconds||0)>0)current.totalMinutes=Math.max(1,Math.round(current.elapsedSeconds/60));current.saved=true;autosave();renderHome();showTab('home')}

let timerInterval=null;
function setWorkoutType(v){current.workoutType=v;autosave()}
function setMeta(){if(!current)return;current.startTime=$('startTime')?.value||current.startTime||'';current.totalMinutes=$('totalMinutes')?.value||'';current.coachNotes=$('coachNotes')?.value||'';current.selfNotes=$('selfNotes')?.value||'';autosave()}
function elapsedNow(){let s=current?.elapsedSeconds||0;if(current?.timerRunning&&current.timerStartedAt)s+=Math.floor((Date.now()-current.timerStartedAt)/1000);return s}
function renderTimer(){if(!current)return;let s=elapsedNow(),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;if($('timerDisplay'))$('timerDisplay').textContent=[h,m,sec].map(x=>String(x).padStart(2,'0')).join(':');if($('timerBtn'))$('timerBtn').textContent=current.timerRunning?'Pause Timer':'Start Timer';clearInterval(timerInterval);if(current.timerRunning)timerInterval=setInterval(renderTimer,1000)}
function toggleTimer(){if(!current)return;if(current.timerRunning)stopTimer();else{if(!current.startTime){let d=new Date();current.startTime=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');$('startTime').value=current.startTime}current.timerRunning=true;current.timerStartedAt=Date.now();autosave();renderTimer()}}
function stopTimer(){if(!current||!current.timerRunning)return;current.elapsedSeconds=elapsedNow();current.timerRunning=false;current.timerStartedAt=null;current.totalMinutes=Math.max(1,Math.round(current.elapsedSeconds/60));if($('totalMinutes'))$('totalMinutes').value=current.totalMinutes;autosave();renderTimer()}
function resetTimer(){if(!current)return;current.elapsedSeconds=0;current.timerRunning=false;current.timerStartedAt=null;current.totalMinutes='';if($('totalMinutes'))$('totalMinutes').value='';autosave();renderTimer()}

function resetDay(){if(confirm('Clear all checks for this workout?')){current.checks={};autosave();renderWorkout()}}
function resumeLast(){let rs=records().sort((a,b)=>b.date.localeCompare(a.date));if(!rs.length)return alert('No workout history yet.');current=rs[0];renderWorkout();showTab('workout')}
function renderHome(){let rs=records().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('recent').innerHTML=rs.length?rs.map(r=>`<div class="historyrow"><div><b>${new Date(r.date+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</b><div class="small">Lesson ${r.lesson} Â· ${r.workoutType||'Independent'}${r.totalMinutes?' Â· '+r.totalMinutes+' min':''}</div></div><div class="pct">${pct(r)}%</div></div>`).join(''):'<div class="pad small">No workouts saved yet.</div>'}
function monday(d){d=new Date(d+'T12:00');let day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return localISO(d)}
function setTarget(){localStorage.setItem('rpgaTarget',$('targetNum').value);renderTarget()}
function renderTarget(){let target=+(localStorage.getItem('rpgaTarget')||4);$('targetNum').value=target;let now=new Date(), y=now.getFullYear(),m=now.getMonth();$('targetMonth').textContent=now.toLocaleDateString(undefined,{month:'long',year:'numeric'});let first=new Date(y,m,1),last=new Date(y,m+1,0),start=new Date(first);start.setDate(start.getDate()-((start.getDay()+6)%7));let out='',rs=records();for(let ws=new Date(start);ws<=last;ws.setDate(ws.getDate()+7)){let days=[];for(let i=0;i<7;i++){let d=new Date(ws);d.setDate(d.getDate()+i);days.push(localISO(d))}let wr=rs.filter(r=>days.includes(r.date)&&pct(r)>0);let unique=[...new Set(wr.map(r=>r.date))];let avg=wr.length?Math.round(wr.reduce((a,r)=>a+pct(r),0)/wr.length):0;out+=`<div class="week"><b>${ws.toLocaleDateString(undefined,{month:'short',day:'numeric'})}â${new Date(ws.getFullYear(),ws.getMonth(),ws.getDate()+6).toLocaleDateString(undefined,{month:'short',day:'numeric'})}: ${unique.length}/${target} ${unique.length>=target?'â':''}</b><div class="small">Days exercised ${unique.length}/7 Â· Avg completion ${avg}%</div><div class="days">${days.map((d,i)=>`<div class="day ${unique.includes(d)?'done':''}">${['M','T','W','T','F','S','S'][i]}<div class="dot">${unique.includes(d)?'â':new Date(d+'T12:00').getDate()}</div></div>`).join('')}</div><div class="progress"><div class="bar" style="width:${Math.min(100,unique.length/target*100)}%"></div></div></div>`} $('weeks').innerHTML=out}
function renderHistory(){let rs=records().sort((a,b)=>b.date.localeCompare(a.date));let now=localISO(),mon=monday(now),month=now.slice(0,7);$('weekCount').textContent=new Set(rs.filter(r=>r.date>=mon&&r.date<=now&&pct(r)>0).map(r=>r.date)).size;$('monthCount').textContent=new Set(rs.filter(r=>r.date.startsWith(month)&&pct(r)>0).map(r=>r.date)).size;$('allHistory').innerHTML=rs.length?rs.map(r=>`<div class="historyrow"><div><b>${new Date(r.date+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</b><div class="small">Lesson ${r.lesson} Â· ${r.workoutType||'Independent'}${r.totalMinutes?' Â· '+r.totalMinutes+' min':''}</div></div><div class="pct">${pct(r)}%</div></div>`).join(''):'<div class="pad small">No workout history yet.</div>'}
function selectedRecords(){let rs=records().filter(r=>pct(r)>0).sort((a,b)=>a.date.localeCompare(b.date)),p=$('period').value,now=localISO();if(p==='week'){let mon=monday(now);rs=rs.filter(r=>r.date>=mon&&r.date<=now)}if(p==='month')rs=rs.filter(r=>r.date.startsWith(now.slice(0,7)));return rs}
function reportString(){let rs=selectedRecords(),avg=rs.length?Math.round(rs.reduce((a,r)=>a+pct(r),0)/rs.length):0,total=rs.reduce((a,r)=>a+(Number(r.totalMinutes)||0),0);return `RPGA Gym â Training Summary
Jordan Ascher

Workouts: ${rs.length}
Average completion: ${avg}%
Total training time: ${total} minutes

`+rs.map(r=>{let note=(r.coachNotes||'').trim();return `${new Date(r.date+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} â Lesson ${r.lesson} â ${pct(r)}%
Type: ${r.workoutType||'Independent'}
Training time: ${r.totalMinutes||0} minutes${r.startTime?' Â· Started '+r.startTime:''}${note?'
Student note: '+note:''}`}).join('

')}
function renderReport(){if(!$('period'))return;$('reportText').textContent=reportString()}
async function shareReport(){let t=reportString();if(navigator.share){try{await navigator.share({title:'RPGA Gym Training Summary',text:t})}catch(e){}}else{location.href='sms:&body='+encodeURIComponent(t)}}
function emailReport(){location.href='mailto:?subject='+encodeURIComponent('RPGA Gym Training Summary â Jordan Ascher')+'&body='+encodeURIComponent(reportString())}
$('workDate').value=localISO();$('today').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
